[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["Pieter Frenssen <pieter@frenssen.be>"]
edition = "2018"

[dependencies]
aoc-runner = "^0.3"
aoc-runner-derive = "^0.3"
indoc = "1.0.3"
regex = "1.4.2"
